### ISSUE TITLE
Issueベース開発レビュー用のIssueを作成

### ISSUE THREAD

**Issue by Shingo-Hajiri** [Shingo-Hajiri/tabitsunagi#44]
## 概要
卒業制作の開発におけるissueを作成しました。
以下、GitHubProjectのURLです。
https://github.com/users/Shingo-Hajiri/projects/1

## 実装予定の機能

- [ ] アカウント登録
- [ ] ログイン/ログアウト
- [ ] 旅行プラン一覧
- [ ] 検索機能
- [ ] 旅行プラン投稿
- [ ] 旅行プラン編集
- [ ] 旅行プラン削除
- [ ] 旅行プラン詳細
- [ ] プロフィール編集
- [ ] マイ旅行プラン一覧
- [ ] SNS共有機能

## 必要なページ

- [ ] トップページ
- [ ] 旅行プラン一覧
- [ ] 旅行プラン詳細
- [ ] ログインページ
- [ ] パスワードリセット
- [ ] パスワード再設定
- [ ] アカウント登録
- [ ] サイトについて
- [ ] プロフィール
- [ ] プロフィール編集
- [ ] メールアドレス変更依頼
- [ ] メールアドレス変更
- [ ] マイ旅行プラン一覧
- [ ] 旅行プラン作成
- [ ] 旅行プラン編集
- [ ] 問い合わせ
- [ ] 利用規約
- [ ] プライバシーポリシー

**Comment by kenchasonakai** [comment]
LGTMです！
