### ISSUE TITLE
卒業制作提出

### ISSUE THREAD

**Issue by Shingo-Hajiri** [Shingo-Hajiri/tabitsunagi#71]
## 各種情報
サービス名: 旅つなぎ
サービスURL: [https://tabi-tsunagi.com/](https://tabi-tsunagi.com/)

投稿者は自分が過去に行った旅行のおすすめのプランとその内容を登録でき、それを共有できます。
閲覧者は旅行のスケジュールを考えるときに他の人の旅行スケジュールを参考にできます。
旅行の計画を立てるより旅行後の思い出やおすすめポイントを記録・共有できるところに重きを置いたサービスです。
サービス名は「旅行」と「数珠つなぎ」の言葉を合わせた造語です。
([特許情報プラットフォーム](https://www.j-platpat.inpit.go.jp/)で同名サービスがないことは確認済みです)

スマホ向けのサービスとして開発をしたため、スマホでご確認いただけますと幸いです。

## READMEレビュー時にMVPリリース時点で実装予定だった機能

- [ ] アカウント登録
- [ ] ログイン/ログアウト
- [ ] 旅行プラン一覧(みんなのおすすめ旅)
- [ ] 検索機能
- [ ] 旅行プラン投稿(おすすめ旅を投稿する)
- [ ] 旅行プラン編集
- [ ] 旅行プラン削除
- [ ] 旅行プラン詳細
- [ ] プロフィール編集
- [ ] マイ旅行プラン一覧(私のおすすめ旅)
- [ ] SNS共有機能

## READMEレビュー時から変更した機能
機能ではありませんが、以下を追加で対応しました。

- [ ] 独自ドメインの取得
- [ ] Google analyticsの導入

## サービスイメージがわかるようなスクリーンショット等
アカウント登録(もしくはログイン)から投稿までの流れです。

### 【初回アクセス時】
1. ヘッダー部分の三アイコンを開き、アカウント登録に遷移
[![Image from Gyazo](https://i.gyazo.com/5c8ca251ce74d7c9669f04c0e49623b2.png)](https://gyazo.com/5c8ca251ce74d7c9669f04c0e49623b2)

2. アカウント登録
[![Image from Gyazo](https://i.gyazo.com/eda410a5af7c8ecd96d0f7a4e0458264.png)](https://gyazo.com/eda410a5af7c8ecd96d0f7a4e0458264)

3.ヘッダー部分の紙飛行機のアイコンから投稿ページへ移動
[![Image from Gyazo](https://i.gyazo.com/ba0264579c49c8eeaad28936a8181a69.png)](https://gyazo.com/ba0264579c49c8eeaad28936a8181a69)

4.投稿する(おすすめスポットは必要に応じて追加できる、オートコンプリート機能実装、画像は投稿完了後に追加できる)
[![Image from Gyazo](https://i.gyazo.com/bf2946ebbb91b8eb3a95132a756db00b.png)](https://gyazo.com/bf2946ebbb91b8eb3a95132a756db00b)

5.みんなの投稿を見る
[投稿サンプル](https://tabi-tsunagi.com/plans/16)

### 【2回目以降のアクセス】
1.ヘッダー部分の→アイコンを開き、ログイン画面に遷移
[![Image from Gyazo](https://i.gyazo.com/5c8ca251ce74d7c9669f04c0e49623b2.png)](https://gyazo.com/5c8ca251ce74d7c9669f04c0e49623b2)

2.ログイン情報を入力
[![Image from Gyazo](https://i.gyazo.com/970ca6a8debbb7ae1d6a48701ed866ef.png)](https://gyazo.com/970ca6a8debbb7ae1d6a48701ed866ef)

※以降は【初回アクセス時】の3.からと同じになります。

**Comment by kenchasonakai** [comment]
LGTMです！

ダークモードだとフォームの入力値が見づらいので調整するとよいかなと思います
[![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/d17322ca5c3bf8e864b05d3fdd2d25b8.png)](https://startup-technology.gyazo.com/d17322ca5c3bf8e864b05d3fdd2d25b8)

**Comment by Shingo-Hajiri** [comment]
ご確認いただきありがとうございます。
また、フォーム部分のご指摘ありがとうございます。
こちら修正してダークモードでも使用しやすいようにいたします。
